---
- hosts: pulp7-n01.rhce.lab
  become: yes
  vars:
    pulp_settings:
      secret_key: "baby"
      content_origin: "https://pulp7-n01.rhce.lab"
    pulp_default_admin_password: "prophet1"
  tasks:
        - name: Create a new repo with name 'my_repo'
          community.general.pulp_repo:
            name: my_repo
            relative_url: my/repo
            state: present

        - name: Create a repo with a feed and a relative URL
          community.general.pulp_repo:
            name: my_centos_updates
            repo_type: rpm
            feed: http://mirror.centos.org/centos/7/updates/x86_64/
            relative_url: centos/7/updates
            url_username: admin
            url_password: admin
            force_basic_auth: yes
            state: present

            #        - name: Remove a repo from the pulp server
            #          community.general.pulp_repo:
            #            name: my_old_repo
            #            repo_type: rpm
            #            state: absent
