---
## This playbook installs and configures AD authentication

- name: Install and configure AD authentication
  hosts: centos  
  become: yes
  become_method: sudo
  vars_prompt:
    - name: "bind_password"
      prompt: "Password for abcdefg\\administrator"
      private: yes

  tasks:
    - name: Install ad_auth required tools
      yum: 
        name: libselinux-python,realmd,sssd,oddjob,oddjob-mkhomedir,adcli,samba-common,samba-common-tools,ntpdate,ntp,python-pip,sudo
        state: present

    - name: Install pexpect using pip
      pip:
        name: pexpect

    - name: Check if machine is bound
      shell: /bin/bash -c "realm list | grep sssd"
      register: realmd_bound
      changed_when: false
      ignore_errors: true

    - name: Join system to AD and put the computer object in the Linux OU
      expect:
        command: /bin/bash -c "/usr/sbin/realm join --user=ADMINISTRATOR@abcdefg.se --computer-ou=OU=Linux,OU=Servers,OU=abcdefg,DC=abcdefg,DC=se abcdefg.se"
        responses:
          Password for *: "{{ bind_password }}"
      when: realmd_bound|failed

    - name: Add default_domain_suffix to sssd.conf
      lineinfile: 
        dest: /etc/sssd/sssd.conf
        line: 'default_domain_suffix = abcdefg.se'
        insertafter: '^\[sssd\]'
      notify:
        - restart sssd
      when: realmd_bound|failed

    - name: Restrict access based on specific ad group
      command: /bin/bash -c "/usr/sbin/realm permit -g g_Server.{{ item }}-logon@abcdefg.se"
      with_items: "{{ inventory_hostname_short }}"
      when: realmd_bound|failed

    - name: Add ad group to sudoers
      lineinfile:
        dest: /etc/sudoers
        line: '%g_Server.{{ item }}-sudo@abcdefg.se        ALL=(ALL)       ALL'
        insertafter: '^%wheel'
      with_items: "{{ inventory_hostname_short }}"
      when: realmd_bound|failed

  handlers:
    - name: restart sssd
      service:
        name: sssd
        state: restarted
