---
- hosts: node1.rhce.lab
  become: yes
  tasks:
    - name: perform a weekly dnf update
      cron:
        name: "weekly dnf update"
        minute: "*"
        hour: "2"
        month: "*"
        weekday: "0"
        user: root
        state: present
        job: "dnf -y update"
