---
- hosts: webservers
  become: yes
  vars:
    content_dir: /var/www/html/webcontent
    http_port: 8080
    admin: rhce
  tasks:
    - name: install httpd
      dnf:
        name: httpd
        state: latest
    - name: push config template
      template:
        src: /home/rhce/Clones/ansible_studies/infra/ansible/templates/http.conf.j2
        dest: /etc/httpd/conf/httpd.conf
        backup: yes
      notify: "restart apache"
    - name: push index.html template
      template:
        src: /home/rhce/Clones/ansible_studies/infra/ansible/templates/index.html.j2
        dest: /var/www/html/webcontent/index.html
  handlers:
    - name: restart web servers
      service:
        name: httpd
        state: restarted
      listen: "restart apache"
