---
- hosts: all
  become: yes
  vars:
    - packages:
      Debian: 
        - ack
      RedHat:
        - ack
  tasks:
    - name: install ack on all hosts that are redhat variant
      package:
        name: "{{ packages[ansible_os_family] }}"
        state: latest
