---
- hosts: $servername
  tasks: 
    - name: Create a File.
      file:
        path: /tmp/testFile
        state: touch 
      register: var
    - name: Display debug message.
      debug: msg="Register output is {{ var }}" 
