---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: shutdown hosts
      command: /sbin/shutdown -h now
      when: ansible_facts['os_family'] == "RedHat"
      ignore_errors: yes
