---
- hosts: node3
  become: yes
  tasks:
    - name: Push the damn info template
      template:
        src: /home/rhce/Clones/ansible_studies/infra/ansible/templates/index.j2
        dest: /tmp/templatedFile
