--- 
- hosts: all
  become: yes
  tasks: 
    - name: install zsh
      dnf:
        name: zsh
        state: latest
    - name: create groups
      group:
        name: "{{ item }}"
        state: present
      loop:
        - devops
        - webadmins
    - name: create arjuna user 
      user: 
        name: arjuna
        comment: arjuna pandu
        shell: /bin/zsh
        groups: wheel,devops,webadmins
        append: yes
        state: present
    - name: create osanyin user 
      user: 
        name: osanyin
        comment: osanyin ngurufinda
        shell: /bin/zsh
        groups: wheel,devops,webadmins
        append: yes
        state: present
