---
- hosts: labservers
  become: yes
  tasks:
    - name: Install Apache
      command: dnf install --quiet -y httpd httpd-devel
    - name: Copy configuration files.
      command: >
        cp httpd.conf /etc/httpd/conf/httpd.conf
      command: >
        cp httpd-vhosts.conf /etc/httpd/conf.d/httpd-vhosts.conf
    - name: Start Apache and configure it to run at boot
      command: systemct start httpd
      command: systemctl enable httpd
